export const DECK_DATA = [
  {
    id: "1",
    title: "Nigerian Music & Afrobeats",
    image: require("../assets/images/deck-images/afrobeats.png"),
    lobbyImage: require("../assets/images/deck-images/afrobeats.png"),
    scoreImage: require("../assets/images/deck-images/afrobeats.png"),
    intro:
      "Feel the rhythm and groove to Nigeria's biggest sounds, artists and dance moves.",
    questions: [
      "Wizkid",
      "Davido",
      "Burna Boy",
      "Fela Kuti",
      "Tiwa Savage",
      "Asake",
      "Rema",
      "Ayra Starr",
      "Olamide",
      "Tems",
      "Fireboy DML",
      "Kizz Daniel",
      "Yemi Alade",
      "Adekunle Gold",
      "Simi",
      "Don Jazzy",
      "P-Square",
      "2Baba",
      "Portable",
      "Shallipopi",
      "Afrobeats",
      "Highlife Music",
      "Fuji Music",
      "Talking Drum",
      "Shaku Shaku",
      "Zanku Dance",
      "Legwork",
      "DJ at a Party",
      "Recording Studio",
      "Music Concert",
    ],
  },

  {
    id: "2",
    title: "Nollywood & Cinema",
    image: require("../assets/images/deck-images/nollywood.png"),
    lobbyImage: require("../assets/images/deck-images/nollywood.png"),
    scoreImage: require("../assets/images/deck-images/nollywood.png"),
    intro:
      "Lights, camera, action! Act out popular Nollywood stars, roles and cinema moments.",
    questions: [
      "Genevieve Nnaji",
      "Funke Akindele",
      "Nkem Owoh",
      "Aki and Pawpaw",
      "Pete Edochie",
      "Patience Ozokwor",
      "Kanayo O. Kanayo",
      "Ramsey Nouah",
      "Mercy Johnson",
      "Odunlade Adekola",
      "Toyín Abraham",
      "Richard Mofe-Damijo",
      "Ini Edo",
      "Osuofia",
      "Village Chief",
      "Strict Stepmother",
      "Village Doctor",
      "Nollywood Director",
      "Movie Audition",
      "Cinema Ticket",
      "Red Carpet",
      "Movie Premiere",
      "Action Scene",
      "Comedy Scene",
      "Crying Scene",
      "Wedding Scene",
      "Village Meeting",
      "Royal Palace",
      "Movie Camera",
      "Film Slate",
    ],
  },

  {
    id: "3",
    title: "Nigerian Cuisine & Delicacies",
    image: require("../assets/images/deck-images/food.png"),
    lobbyImage: require("../assets/images/deck-images/food.png"),
    scoreImage: require("../assets/images/deck-images/food.png"),
    intro:
      "Taste the flavour and spice of Nigeria's favourite meals, snacks and drinks.",
    questions: [
      "Jollof Rice",
      "Fried Rice",
      "Pounded Yam",
      "Egusi Soup",
      "Pepper Soup",
      "Suya",
      "Puff Puff",
      "Moi Moi",
      "Akara",
      "Amala",
      "Ewedu",
      "Gbegiri",
      "Efo Riro",
      "Ofada Rice",
      "Nkwobi",
      "Abacha",
      "Boli",
      "Roasted Corn",
      "Chin Chin",
      "Meat Pie",
      "Gala",
      "Kilishi",
      "Garri",
      "Groundnut",
      "Plantain Chips",
      "Zobo",
      "Palm Wine",
      "Party Jollof",
      "Cooking With Firewood",
      "Eating With Your Hands",
    ],
  },

  {
    id: "4",
    title: "Nigerian Slang & Street Lingo",
    image: require("../assets/images/deck-images/slangs.png"),
    lobbyImage: require("../assets/images/deck-images/slangs.png"),
    scoreImage: require("../assets/images/deck-images/slangs.png"),
    intro:
      "No wahala! Test how well your team understands popular Nigerian expressions.",
    questions: [
      "No Wahala",
      "How Far?",
      "I Dey",
      "Omo!",
      "E Choke",
      "Gbege",
      "Wahala",
      "Abeg",
      "Oya",
      "Sharp Sharp",
      "Japa",
      "Sapa",
      "Cruise",
      "Vawulence",
      "Breakfast",
      "Bad Belle",
      "Pepper Dem",
      "Ajebutter",
      "Ajepako",
      "Trenches",
      "We Outside",
      "Who You Help?",
      "Shey You Dey Whine Me?",
      "Na So",
      "E Go Better",
      "God Abeg",
      "Las Las",
      "I No Fit Shout",
      "Area Boy",
      "Soft Life",
    ],
  },

  {
    id: "5",
    title: "Landmarks & Geography",
    image: require("../assets/images/deck-images/landmark.png"),
    lobbyImage: require("../assets/images/deck-images/landmark.png"),
    scoreImage: require("../assets/images/deck-images/landmark.png"),
    intro:
      "Travel around Nigeria through famous cities, landmarks and natural wonders.",
    questions: [
      "Olumo Rock",
      "Zuma Rock",
      "Aso Rock",
      "Third Mainland Bridge",
      "National Theatre",
      "Lekki Conservation Centre",
      "Obudu Mountain Resort",
      "Yankari Game Reserve",
      "Erin Ijesha Waterfalls",
      "Idanre Hills",
      "Tarkwa Bay",
      "Eko Atlantic",
      "Freedom Park",
      "Nike Art Gallery",
      "Millennium Park",
      "River Niger",
      "River Benue",
      "Lagos",
      "Abuja",
      "Ibadan",
      "Kano",
      "Port Harcourt",
      "Calabar",
      "Enugu",
      "Benin City",
      "Jos",
      "Abeokuta",
      "Niger Bridge",
      "Kainji Dam",
      "Atlantic Ocean",
    ],
  },

  {
    id: "6",
    title: "Fashion & Style",
    image: require("../assets/images/deck-images/fashion.png"),
    lobbyImage: require("../assets/images/deck-images/fashion.png"),
    scoreImage: require("../assets/images/deck-images/fashion.png"),
    intro:
      "Show off traditional and modern Nigerian fashion through poses and actions.",
    questions: [
      "Agbada",
      "Ankara",
      "Aso Oke",
      "Gele",
      "Isi Agu",
      "Senator Wear",
      "Buba and Sokoto",
      "Kaftan",
      "Lace Material",
      "George Wrapper",
      "Traditional Beads",
      "Fila Cap",
      "Head Tie",
      "Palm Slippers",
      "High Heels",
      "Dark Sunglasses",
      "Face Cap",
      "Dreadlocks",
      "Braids",
      "Barbing Hair",
      "Fashion Designer",
      "Runway Model",
      "Tailor",
      "Taking Measurements",
      "Tying a Gele",
      "Ironing Clothes",
      "Sewing a Dress",
      "Polishing Shoes",
      "Wedding Outfit",
      "Matching Family Outfit",
    ],
  },

  {
    id: "7",
    title: "Nigerian Football",
    image: require("../assets/images/deck-images/football.png"),
    lobbyImage: require("../assets/images/deck-images/football.png"),
    scoreImage: require("../assets/images/deck-images/football.png"),
    intro:
      "Celebrate Nigerian football stars, teams and unforgettable match moments.",
    questions: [
      "Jay-Jay Okocha",
      "Victor Osimhen",
      "Kanu Nwankwo",
      "Mikel Obi",
      "Ahmed Musa",
      "Vincent Enyeama",
      "Rashidi Yekini",
      "Asisat Oshoala",
      "Sunday Oliseh",
      "Alex Iwobi",
      "Super Eagles",
      "Super Falcons",
      "Enyimba FC",
      "Goalkeeper",
      "Referee",
      "Penalty Kick",
      "Free Kick",
      "Corner Kick",
      "Red Card",
      "Yellow Card",
      "Offside",
      "Goal Celebration",
      "Penalty Shootout",
      "Football Commentary",
      "Football Supporter",
      "Team Captain",
      "Injured Player",
      "Missing an Open Goal",
      "Lifting a Trophy",
      "Playing Street Football",
    ],
  },

  {
    id: "8",
    title: "Nigerian Tech & Hustle",
    image: require("../assets/images/deck-images/tech.png"),
    lobbyImage: require("../assets/images/deck-images/tech.png"),
    scoreImage: require("../assets/images/deck-images/tech.png"),
    intro:
      "Act out Nigeria's technology, businesses and everyday hustle culture.",
    questions: [
      "Software Developer",
      "Graphic Designer",
      "Content Creator",
      "Tech Founder",
      "Laptop",
      "Mobile App",
      "Video Call",
      "Slow Internet",
      "Wi-Fi Password",
      "Power Bank",
      "Phone Charger",
      "Computer Village",
      "POS Attendant",
      "Dispatch Rider",
      "Online Vendor",
      "Remote Worker",
      "Social Media Manager",
      "Typing Very Fast",
      "Broken Phone Screen",
      "Forgotten Password",
      "Bank Transfer",
      "Debit Alert",
      "Data Subscription",
      "Generator",
      "Power Outage",
      "Job Interview",
      "Working Overtime",
      "Customer Support",
      "Taking a Screenshot",
      "Phone Software Update",
    ],
  },

  {
    id: "9",
    title: "Lagos Life & Transport",
    image: require("../assets/images/deck-images/lagos.png"),
    lobbyImage: require("../assets/images/deck-images/lagos.png"),
    scoreImage: require("../assets/images/deck-images/lagos.png"),
    intro:
      "Experience the traffic, transport and energy of everyday Lagos life.",
    questions: [
      "Danfo Bus",
      "Keke Napep",
      "Okada",
      "BRT Bus",
      "Lagos Traffic",
      "Bus Conductor",
      "LASTMA Officer",
      "Crossing the Road",
      "Running After a Bus",
      "Entering a Crowded Bus",
      "Paying Transport Fare",
      "Bus Stop",
      "Car Horn",
      "Traffic Light",
      "Pothole",
      "Third Mainland Bridge",
      "Lekki Toll Gate",
      "Balogun Market",
      "Computer Village",
      "CMS",
      "Oshodi",
      "Yaba",
      "Surulere",
      "Victoria Island",
      "Eko Hotel",
      "Street Hawker",
      "Gala Seller",
      "Rainy-Day Traffic",
      "Looking for Change",
      "Missing Your Bus Stop",
    ],
  },

  {
    id: "10",
    title: "School Life",
    image: require("../assets/images/deck-images/school.png"),
    lobbyImage: require("../assets/images/deck-images/school.png"),
    scoreImage: require("../assets/images/deck-images/school.png"),
    intro: "Relive familiar classroom, examination and campus experiences.",
    questions: [
      "School Assembly",
      "Class Captain",
      "Strict Teacher",
      "Late Student",
      "Morning Attendance",
      "School Bell",
      "Homework",
      "Group Assignment",
      "Surprise Test",
      "Final Examination",
      "Invigilator",
      "Writing Notes",
      "Borrowing a Pen",
      "Reading in the Library",
      "Sleeping in Class",
      "Answering a Question",
      "Raising Your Hand",
      "School Uniform",
      "Lunch Break",
      "Sports Day",
      "Graduation",
      "Report Card",
      "Missing Assignment",
      "Online Class",
      "Science Laboratory",
      "Computer Class",
      "School Principal",
      "Best Student",
      "Hostel Life",
      "Campus Shuttle",
    ],
  },

  {
    id: "11",
    title: "Professions & Occupations",
    image: require("../assets/images/deck-images/profession.png"),
    lobbyImage: require("../assets/images/deck-images/profession.png"),
    scoreImage: require("../assets/images/deck-images/profession.png"),
    intro:
      "Act out familiar professionals and the work they perform every day.",
    questions: [
      "Doctor",
      "Nurse",
      "Teacher",
      "Lawyer",
      "Judge",
      "Police Officer",
      "Firefighter",
      "Pilot",
      "Chef",
      "Farmer",
      "Tailor",
      "Barber",
      "Mechanic",
      "Electrician",
      "Plumber",
      "Carpenter",
      "Photographer",
      "Journalist",
      "News Presenter",
      "Actor",
      "Musician",
      "Footballer",
      "Software Developer",
      "Architect",
      "Engineer",
      "Banker",
      "Market Trader",
      "Bus Driver",
      "Security Guard",
      "Delivery Rider",
    ],
  },

  {
    id: "12",
    title: "Nigerian Culture & Traditions",
    image: require("../assets/images/deck-images/culture.png"),
    lobbyImage: require("../assets/images/deck-images/culture.png"),
    scoreImage: require("../assets/images/deck-images/culture.png"),
    intro:
      "Explore Nigeria's rich traditions, languages, ceremonies and cultural practices.",
    questions: [
      "Traditional Ruler",
      "Village Chief",
      "Talking Drum",
      "Masquerade",
      "Traditional Dancer",
      "Naming Ceremony",
      "Traditional Wedding",
      "Bride Price",
      "Kola Nut",
      "Palm Wine",
      "Village Square",
      "Town Crier",
      "Royal Palace",
      "Chief's Cap",
      "Coral Beads",
      "Prostrating to Greet",
      "Kneeling to Greet",
      "Respecting Elders",
      "Family Compound",
      "New Yam Festival",
      "Durbar Festival",
      "Calabar Carnival",
      "Eyo Festival",
      "Cultural Day",
      "Local Language",
      "Folktale",
      "Moonlight Story",
      "Traditional Drumming",
      "Community Meeting",
      "Harvest Celebration",
    ],
  },

  {
    id: "13",
    title: "Parties & Celebrations",
    image: require("../assets/images/deck-images/party.png"),
    lobbyImage: require("../assets/images/deck-images/party.png"),
    scoreImage: require("../assets/images/deck-images/party.png"),
    intro: "Bring the energy of Nigerian parties, weddings and celebrations.",
    questions: [
      "Birthday Party",
      "Wedding Reception",
      "Naming Ceremony",
      "Graduation Party",
      "Surprise Party",
      "DJ",
      "Master of Ceremony",
      "Wedding Cake",
      "Birthday Cake",
      "Party Jollof",
      "Souvenir",
      "Matching Aso Ebi",
      "Spraying Money",
      "Dance Competition",
      "Photo Booth",
      "Taking a Selfie",
      "Wedding Photographer",
      "Cutting the Cake",
      "Catching the Bouquet",
      "Bride and Groom",
      "Best Man",
      "Bridesmaid",
      "Party Invitation",
      "Opening a Gift",
      "Blowing Candles",
      "Singing Happy Birthday",
      "Arriving Late",
      "Dancing in a Circle",
      "Sharing Food",
      "Cleaning After the Party",
    ],
  },

  {
    id: "14",
    title: "Animals & Nature",
    image: require("../assets/images/deck-images/animal.png"),
    lobbyImage: require("../assets/images/deck-images/animal.png"),
    scoreImage: require("../assets/images/deck-images/animal.png"),
    intro: "Imitate familiar animals, weather and natural environments.",
    questions: [
      "Lion",
      "Elephant",
      "Monkey",
      "Goat",
      "Chicken",
      "Cow",
      "Dog",
      "Cat",
      "Snake",
      "Crocodile",
      "Fish",
      "Frog",
      "Mosquito",
      "Butterfly",
      "Parrot",
      "Eagle",
      "Tortoise",
      "Snail",
      "Lizard",
      "Horse",
      "Heavy Rain",
      "Thunder",
      "Lightning",
      "Strong Wind",
      "Hot Sun",
      "Rainbow",
      "River",
      "Waterfall",
      "Climbing a Tree",
      "Planting a Seed",
    ],
  },

  {
    id: "15",
    title: "Everyday Actions",
    image: require("../assets/images/deck-images/actions.png"),
    lobbyImage: require("../assets/images/deck-images/actions.png"),
    scoreImage: require("../assets/images/deck-images/actions.png"),
    intro: "Act out simple everyday activities without saying a word.",
    questions: [
      "Brushing Your Teeth",
      "Taking a Shower",
      "Combing Your Hair",
      "Getting Dressed",
      "Tying Your Shoes",
      "Eating Breakfast",
      "Drinking Water",
      "Washing Plates",
      "Sweeping the Floor",
      "Mopping the Floor",
      "Cooking Food",
      "Opening a Door",
      "Locking a Door",
      "Making a Phone Call",
      "Sending a Message",
      "Taking a Picture",
      "Watching Television",
      "Reading a Book",
      "Writing a Letter",
      "Running",
      "Jumping",
      "Swimming",
      "Dancing",
      "Singing",
      "Laughing",
      "Crying",
      "Sneezing",
      "Yawning",
      "Sleeping",
      "Waking Up Late",
    ],
  },
];
