import * as Icons from "phosphor-react-native";

export const DECK_DATA = [
  {
    id: "1",
    title: "Nigerian Music & Afrobeats",
    icon: Icons.MusicalNote,
    // bgImage: require("../assets/images/musicBg.png"),
    // lobbyImg: require("../assets/images/musicLobbyImg.png"),
    intro:
      "Feel the rhythm and groove to the global sound! Test your knowledge of iconic Afrobeats artists, classic dance steps, and industry anthems.",
    questions: [
      "Wizkid",
      "Fela Kuti",
      "Davido",
      "Burna Boy",
      "Tiwa Savage",
      "Zanku",
      "Last Last",
      "Palava",
      "Asake",
      "Olamide",
      "Buga",
      "Yabaleft",
      "Don Jazzy",
      "Tiwa's Vibe",
      "Essence",
      "Portable",
      "Legwork",
      "Ayra Starr",
      "Kokoma",
      "Shoki",
    ],
  },
  {
    id: "2",
    title: "Nollywood & Cinema",
    icon: Icons.FilmSlate,
    // bgImage: require("../assets/images/nollywoodBg.png"),
    // lobbyImg: require("../assets/images/nollywoodLobbyImg.png"),
    intro:
      "Lights, Camera, Action! Dive into the heart of African cinema with the ultimate Nollywood challenge. Think you know your movie trivia? Prove it on the screen.",
    questions: [
      "Nkem Owoh (Osuofia)",
      "Living in Bondage",
      "Aki and Pawpaw",
      "Genevieve Nnaji",
      "Chief",
      "Ramsey Nouah",
      "Patience Ozokwo (Mama G)",
      "King of Boys",
      "Funke Akindele",
      "The Village Priest",
      "Pete Edochie",
      "Blood Sisters",
      "The Evil Stepmother",
      "Ramsey's Loverboy Stare",
      "Kanayo O. Kanayo",
      "Omo Ghetto",
      "The Native Doctor (Babalawo)",
      "Rita Dominic",
      "The Wedding Party",
      "Tonto Dikeh",
    ],
  },
  {
    id: "3",
    title: "Nigerian Cuisine & Delicacies",
    icon: Icons.BowlFood,
    // bgImage: require("../assets/images/cuisineBg.png"),
    // lobbyImg: require("../assets/images/cuisineLobbyImg.png"),
    intro:
      "Taste the flavor and spice! From party Jollof to savory swallows, bring Nigeria's richest culinary delights to life through actions.",
    questions: [
      "Jollof Rice",
      "Pounded Yam and Egusi",
      "Suya",
      "Puff Puff",
      "Pepper Soup",
      "Amala and Gbegiri",
      "Moi Moi",
      "Efo Riro",
      "Plantain (Dodo)",
      "Nkwobi",
      "Garri and Ice Water",
      "Kilishi",
      "Boli and Groundnut",
      "Chin Chin",
      "Abacha (African Salad)",
      "Fried Rice",
      "Ofada Rice and Sauce",
      "Akara",
      "Peppered Snail",
      "Asun",
    ],
  },
  {
    id: "4",
    title: "Nigerian Slang & Street Lingo",
    icon: Icons.ChatBubble,
    // bgImage: require("../assets/images/slangBg.png"),
    // lobbyImg: require("../assets/images/slangLobbyImg.png"),
    intro:
      "No wahala! Speak the true street language of the mainland and island. Show off your urban lingo and quick expressions.",
    questions: [
      "Omo!",
      "No Wahala",
      "Mainland",
      "Wahala dey",
      "Shey you dey whine me?",
      "E choke!",
      "Gbege",
      "Jagaban",
      "Pepper dem",
      "Ajebutter",
      "Ajepako",
      "Ori mi",
      "Oya na",
      "Shey you mad?",
      "Trenches",
      "We outside",
      "No cap",
      "Cast",
      "Breakfast",
      "Bad belle",
    ],
  },
  {
    id: "5",
    title: "Landmarks & Geography",
    icon: Icons.MapPin,
    // bgImage: require("../assets/images/landmarksBg.png"),
    // lobbyImg: require("../assets/images/landmarksLobbyImg.png"),
    intro:
      "Journey across the giant of Africa! Mimic iconic bridges, magnificent rocks, and unforgettable urban landmarks.",
    questions: [
      "Olumo Rock",
      "Lekki-Ikoyi Link Bridge",
      "Zuma Rock",
      "Yankari Game Reserve",
      "Eko Atlantic",
      "Third Mainland Bridge",
      "National Theatre, Iganmu",
      "Aso Rock",
      "Nike Art Gallery",
      "Tarkwa Bay",
      "Olumirin Waterfalls (Erin Ijesha)",
      "Idanre Hills",
      "Lekki Conservation Centre",
      "Millennium Park",
      "National Stadium, Surulere",
      "The Niger Bridge (Onitsha)",
      "Murtala Muhammed International Airport",
      "Obudu Mountain Resort",
      "Freedom Park, Lagos",
      "Kainji Dam",
    ],
  },
  {
    id: "6",
    title: "Fashion & Style",
    icon: Icons.TShirt,
    // bgImage: require("../assets/images/fashionBg.png"),
    // lobbyImg: require("../assets/images/fashionLobbyImg.png"),
    intro:
      "Step out in absolute grand style! Strut, tie your gele, and flaunt the finest traditional and modern Nigerian fits.",
    questions: [
      "Aso Oke",
      "Agbada",
      "Ankara",
      "Gele",
      "Crocs",
      "Cap (Fila)",
      "Babariga",
      "Itsekiri George wrapper",
      "Senator wear",
      "Beaded coral necklace (Ikelu)",
      "Isi Agu",
      "Buba and Sokoto",
      "Bling-bling wrist watch",
      "Palm slippers",
      "Face cap backward",
      "Dreadlocks",
      "Lace material",
      "Turban",
      "Shades indoors",
      "Designer belt",
    ],
  },
  {
    id: "7",
    title: "Nigerian Football",
    icon: Icons.SoccerBall,
    // bgImage: require("../assets/images/footballBg.png"),
    // lobbyImg: require("../assets/images/footballLobbyImg.png"),
    intro:
      "Up Super Eagles! Relive legendary goals, historic tournaments, and the unrivaled passion of Nigerian football.",
    questions: [
      "Jay-Jay Okocha",
      "Super Eagles",
      "Victor Osimhen",
      "Goal na Goal",
      "Super Sub",
      "Kanu Nwankwo",
      "Vincent Enyeama",
      "Rashidi Yekini",
      "Ahmed Musa",
      "The 1994 Atlanta Olympics Gold",
      "Up Super Eagles!",
      "The Green Jersey",
      "Sunday Oliseh",
      "Asisat Oshoala",
      "Enyimba FC",
      "Penalty shootout anxiety",
      "The Vuvuzela sound",
      "John Mikel Obi",
      "Red card referee drama",
      "Super fan with drums",
    ],
  },
  {
    id: "8",
    title: "Nigerian Tech & Hustle",
    icon: Icons.Briefcase,
    // bgImage: require("../assets/images/hustleBg.png"),
    // lobbyImg: require("../assets/images/hustleLobbyImg.png"),
    intro:
      "The Lagos grind never stops! From Danfo drivers to tech founders, act out the daily hustle that keeps the nation moving.",
    questions: [
      "Danfo Driver",
      "Okada Rider",
      "POS Attendant",
      "Chowdeck",
      "Traffic along Third Mainland",
      "Generator repairer",
      "Buy your Gala here!",
      "Tailor saying Come back next week",
      "Keke Napep",
      "Cowry Card",
      "Flutterwave",
      "PiggyVest",
      "Street phone charger",
      "Area boys levy collector",
      "Computer Village hustler",
      "Dispatch rider weaving through traffic",
      "Scavenger pushing cart",
      "Car wash boy throwing water bucket",
      "Bricklayer on a scaffold",
      "Shoe cobbler with nails in mouth",
    ],
  },
  {
    id: "9",
    title: "Nigerian Proverbs & Sayings",
    icon: Icons.BookOpen,
    // bgImage: require("../assets/images/proverbsBg.png"),
    // lobbyImg: require("../assets/images/proverbsLobbyImg.png"),
    intro:
      "Proverbs are the palm-oil with which words are eaten. Act out wisdom, witty adages, and classic parental warnings.",
    questions: [
      "Monkey dey work, baboon dey chop",
      "E don cast",
      "Had I known is always last",
      "Water wey carry frog, wet go carry toad?",
      "He who must eat honey must face the bee",
      "No condition is permanent",
      "Patient dog eats the fattest bone",
      "Las las, everybody go breakfast",
      "A bird in hand is worth two in the bush",
      "When push comes to shove",
      "Procrastination is the thief of time",
      "Talk true make I beat you",
      "Empty barrel makes the loudest noise",
      "Trouble dey sleep, nyanga go wake am",
      "Dry meat catch pepper",
      "God pass man",
      "Proverbs are the palm-oil with which words are eaten",
      "If I start to talk, everywhere go burst",
      "Follow person wey know road",
      "Tomorrow na tomorrow",
    ],
  },
  {
    id: "10",
    title: "Owambe Culture",
    icon: Icons.Confetti,
    // bgImage: require("../assets/images/owambeBg.png"),
    // lobbyImg: require("../assets/images/owambeLobbyImg.png"),
    intro:
      "Party like a true Omo Eko! Spray money, secure your souvenir bucket, and vibe to the live band at the ultimate Owambe.",
    questions: [
      "Aso Ebi",
      "Small Chops",
      "Souvenirs",
      "Spraying money",
      "Jollof rice and cold Malta",
      "The MC hyping the crowd",
      "Live Band trumpeter",
      "Carrying coolers of food home",
      "Beating the Talking Drum",
      "The usher blocking the door",
      "Tying Gele too tight",
      "Dancing with currency notes on forehead",
      "The grumpy elder",
      "Chasing the souvenir distributor",
      "Saturday morning street tents",
      "The photographer with flash",
      "Opening prayer that takes 30 minutes",
      "Owanbe Saturday",
      "Sharing chilled Chapman",
      "Cutting the giant wedding cake",
    ],
  },
  {
    id: "11",
    title: "Childhood Memories",
    icon: Icons.Child,
    // bgImage: require("../assets/images/childhoodBg.png"),
    // lobbyImg: require("../assets/images/childhoodLobbyImg.png"),
    intro:
      "Take a nostalgic trip down memory lane! Relive school days, compound chores, and iconic childhood treats.",
    questions: [
      "Close the gate!",
      "Gala and La Casera",
      "Common Entrance exam stress",
      "Boarding School prep time",
      "Flash me, I'll flash you",
      "Filling water in jerry cans",
      "Watching Tales by Moonlight",
      "Singing National Anthem in the sun",
      "Slap and Die playground game",
      "Buying pure water by biting the edge",
      "Mathematical set compass accidents",
      "Chasing after the Fan Milk bike",
      "Tinker Taylor Soldier Sailor game",
      "Using broomsticks to sweep compound",
      "Writing Keep off on notebooks",
      "Buying sweet colored icing biscuit",
      "The fear of cane from strict teacher",
      "Playing football with taped nylon ball",
      "Writing lines 100 times",
      "Hiding the TV remote",
    ],
  },
  {
    id: "12",
    title: "Nigerian Markets",
    icon: Icons.Storefront,
    // bgImage: require("../assets/images/marketsBg.png"),
    // lobbyImg: require("../assets/images/marketsLobbyImg.png"),
    intro:
      "Bargain your best price! Navigate the chaotic, bustling energy of Balogun, Alaba, and open-air trade hubs.",
    questions: [
      "Balogun Market",
      "Alaba International",
      "Bargain the price",
      "Stockfish",
      "Price for last",
      "Ariaria Market (Aba)",
      "Oshodi market chaos",
      "Yaba market thrift shopping",
      "Pulling a customer by hand",
      "Counting old dirty Naira notes",
      "Buying wrapper by yards",
      "Smelling dried pepper and crayfish",
      "Arguing over change",
      "Carrying heavy load on head",
      "Snail basket tipping over",
      "Buying cow foot chunks",
      "Sound of coin in wooden savings box",
      "Pointing at fabric rolls on shelf",
      "Buying fake electronic cables",
      "Bring market money!",
    ],
  },
  {
    id: "13",
    title: "Professions & Characters",
    icon: Icons.UserGroup,
    // bgImage: require("../assets/images/professionsBg.png"),
    // lobbyImg: require("../assets/images/professionsLobbyImg.png"),
    intro:
      "Meet the familiar faces of the neighborhood! From NEPA officials to stubborn tailors, act out iconic everyday characters.",
    questions: [
      "NEPA Official",
      "Area Boy",
      "Tailor",
      "Vulcanizer fixing a flat tire",
      "Market Woman yelling at debtors",
      "School Security Guard",
      "Roadside Prophet with megaphone",
      "Corper looking lost",
      "Pure Water seller balancing tray",
      "Bank Teller on a Friday afternoon",
      "Police officer at a checkpoint",
      "The neighborhood gossip",
      "Bricklayer mixing cement",
      "School Principal with long cane",
      "Street food vendor blowing fan on coals",
      "Pharmacy chemist prescribing agbo",
      "Okada rider arguing over balance",
      "Church usher directing to overflow",
      "Scavenger searching through trash",
      "Newspaper vendor displaying headlines",
    ],
  },
  {
    id: "14",
    title: "History & Independence",
    icon: Icons.Flag,
    // bgImage: require("../assets/images/historyBg.png"),
    // lobbyImg: require("../assets/images/historyLobbyImg.png"),
    intro:
      "Honor the giants of the past! Celebrate the milestones, leaders, and rich history that shaped Nigeria.",
    questions: [
      "October 1st",
      "Green-White-Green flag",
      "Chief Obafemi Awolowo",
      "Lord Lugard",
      "1914 Amalgamation",
      "Sir Abubakar Tafawa Balewa",
      "Nnamdi Azikiwe",
      "June 12th Democracy Day",
      "1960 Independence Day celebration",
      "General Murtala Muhammed",
      "Queen Elizabeth II visiting Nigeria",
      "Herbert Macaulay",
      "The Nigerian Civil War history",
      "Funmilayo Ransome-Kuti",
      "Creation of 36 states",
      "Murtala Muhammed Airport naming",
      "Nigerian Naira introduction",
      "Jaja of Opobo",
      "Queen Amina of Zaria",
      "1999 Constitution transition",
    ],
  },
  {
    id: "15",
    title: "Memes & Internet Culture",
    icon: Icons.DevicePhoneMobile,
    // bgImage: require("../assets/images/memesBg.png"),
    // lobbyImg: require("../assets/images/memesLobbyImg.png"),
    intro:
      "Pure cruise and viral trends! Bring internet humor, Twitter NG banter, and unforgettable viral sensations to life.",
    questions: [
      "What is your type?",
      "God when",
      "It is well",
      "VeryDarkMan",
      "Why are you running?",
      "Aza",
      "God abeg",
      "Basketmouth comedy skits",
      "Broda Shaggi acting dramatic",
      "Tunde Ednut repost notification",
      "Shey you see wetin you cause?",
      "Wahala for who no get money",
      "Portable jumping on top of a car",
      "Subscribe to my channel",
      "Dem go explain tire",
      "Odogwu behavior",
      "Pepper them gang",
      "Twitter NG dragging session",
      "You want to bambam?",
      "Wahala be like bicycle",
    ],
  },
];
