import * as Icons from "phosphor-react-native";

export const DECK_DATA = [
  {
    id: "1",
    title: "Nollywood Stars",
    icon: Icons.FilmSlate,
    bgImage: require("../assets/images/nollywoodBg.png"),
    lobbyImg: require("../assets/images/nollywoodLobbyImg.png"),
    intro:
      "Lights, Camera, Action! Dive into the heart of African cinema with the ultimate Nollywood challenge. Think you know your movie trivia? Prove it on the screen.",
    questions: [
      "Genevieve Nnaji",
      "Ramsey Nouah",
      "Funke Akindele",
      "Pete Edochie",
      "Odunlade Adekola",
      "Nkem Owoh",
      "Patience Ozokwor",
      "Rita Dominic",
      "Desmond Elliot",
      "Mercy Johnson",
      "Ik Ogbonna",
      "Kanayo O. Kanayo",
      "Toyin Abraham",
      "Richard Mofe-Damijo",
      "Sola Sobowale",
      "Osita Iheme",
      "Chinedu Ikedieze",
      "Tonto Dikeh",
      "Jim Iyke",
      "Stephanie Okereke",
    ],
  },
  {
    id: "2",
    title: "Afrobeats",
    icon: Icons.MusicNotes,
    intro:
      "Feel the rhythm and drop the bass! From Lagos to the world, test how fast you can name the biggest sounds, stars, and anthems defining global music culture.",
    questions: [
      "Wizkid",
      "Burna Boy",
      "Davido",
      "Tiwa Savage",
      "Asake",
      "Rema",
      "Omah Lay",
      "Ayra Starr",
      "Buju BNXN",
      "Fireboy DML",
      "Olamide",
      "Tekno",
      "Yemi Alade",
      "Kizz Daniel",
      "Portable",
      "Ckay",
      "Zlatan",
      "Adekunle Gold",
      "Simi",
      "Seyi Vibez",
    ],
  },
  {
    id: "3",
    title: "Lagos Life",
    icon: Icons.Buildings,
    intro:
      "Eko o ni baje! Navigate the hustle, the traffic, the island flex, and the mainland grit of Africa's most vibrant mega-city.",
    questions: [
      "Third Mainland Bridge",
      "Danfo Bus",
      "Molue",
      "Traffic Jam",
      "Balogun Market",
      "Lekki Phase 1",
      "Victoria Island",
      "Kano Street",
      "Agege Bread",
      "Ojuelegba",
      "Tafawa Balewa Square",
      "Ikorodu Road",
      "Yellow Bus Conductor",
      "Owambe",
      "National Theatre",
      "CMS Bus Stop",
      "Banana Island",
      "Epe Expressway",
      "Street Hawkers",
      "Area Boys",
    ],
  },
  {
    id: "4",
    title: "Street Food",
    icon: Icons.Hamburger,
    intro:
      "Your mouth is about to water. From roadside grills to local joints, test your knowledge of the ultimate street delicacies.",
    questions: [
      "Suya",
      "Bole and Fish",
      "Puff Puff",
      "Akara",
      "Ewa Agoyin",
      "Mosa",
      "Roasted Corn and Pear",
      "Abacha",
      "Nkwobi",
      "Isiewu",
      "Kilishi",
      "Fried Yam",
      "Plantain Chips",
      "Agege Bread and Ewa",
      "Boiled Groundnuts",
      "Garri and Sugar",
      "Kuli Kuli",
      "Chin Chin",
      "Zobo Drink",
      "Palm Wine",
    ],
  },
  {
    id: "5",
    title: "Pidgin",
    icon: Icons.ChatCircleText,
    intro:
      "No carry last! Speak the lingua franca that connects every street, corner, and market across the federation.",
    questions: [
      "How far",
      "No wahala",
      "Wetin dey happen",
      "E go better",
      "Chop life",
      "Carry go",
      "Gbe body e",
      "Jagbajantis",
      "Omo",
      "Abeg",
      "Wahala for who",
      "Pepper dem",
      "Maga",
      "Yab",
      "Gist",
      "Gra Gra",
      "Broke pin",
      "Form am",
      "Sef",
      "Kasala",
    ],
  },
  {
    id: "6",
    title: "Football",
    icon: Icons.SoccerBall,
    intro:
      "From Super Eagles legends to European night games, show that you know your goals, cards, and football icons.",
    questions: [
      "Jay-Jay Okocha",
      "Nwankwo Kanu",
      "Victor Osimhen",
      "Asisat Oshoala",
      "Super Eagles",
      "Premier League",
      "Offside",
      "Penalty Shootout",
      "Yellow Card",
      "Red Card",
      "Hat Trick",
      "VAR",
      "Champions League",
      "Goalie",
      "Corner Kick",
      "Free Kick",
      "Finidi George",
      "John Mikel Obi",
      "Ahmed Musa",
      "Vicente Enyeama",
    ],
  },
  {
    id: "7",
    title: "Market",
    icon: Icons.ShoppingBag,
    intro:
      "Haggling is an Olympic sport here. Can you name the iconic items, crowded alleys, and trader terms of local open-air markets?",
    questions: [
      "Balogun Market",
      "Alaba International",
      "Computer Village",
      "Yaba Market",
      "Onitsha Main Market",
      "Ariaria Market",
      "Haggling Price",
      "Last Price",
      "Change for Change",
      "Wholesale",
      "Retail Trader",
      "Aso Oke",
      "Ankara Fabric",
      "Bales of Clothes",
      "Iya Basira",
      "Store Owner",
      "Customer",
      "Barrow Pusher",
      "Load Carrier",
      "Market Union",
    ],
  },
  {
    id: "8",
    title: "Party",
    icon: Icons.Confetti,
    intro:
      "Aso Ebi locked down and speakers blasting. Bring the Saturday Owambe energy straight to the game screen.",
    questions: [
      "Owambe",
      "Aso Ebi",
      "Jollof Rice",
      "Small Chops",
      "Share the Souvenirs",
      "Spraying Money",
      "Band Stand",
      "Master of Ceremonies",
      "Gele",
      "Agbada",
      "Zanku Dance",
      "Gbese",
      "Stepping on toes",
      "Extra Plate",
      "Cooler of Food",
      "Champagne",
      "Hype Man",
      "Dance Competition",
      "Bridal Train",
      "After Party",
    ],
  },
  {
    id: "9",
    title: "Tech",
    icon: Icons.Desktop,
    intro:
      "From Silicon Valley to Yaba Silicon Lagoon. Test your knowledge of code, gadgets, startups, and digital hustle.",
    questions: [
      "JavaScript",
      "React Native",
      "Next.js",
      "Bug Fix",
      "Stack Overflow",
      "GitHub Commit",
      "Frontend Developer",
      "Backend API",
      "Terminal Command",
      "Dark Mode",
      "Wi-Fi Router",
      "Smartphone",
      "Crypto Wallet",
      "Power Bank",
      "Generator Noise",
      "Fibre Internet",
      "Database Query",
      "Infinite Loop",
      "Deploy to Production",
      "Coffee Mug",
    ],
  },
  {
    id: "10",
    title: "Classic",
    icon: Icons.MaskHappy,
    intro:
      "Timeless everyday objects, pop culture icons, and universally recognizable terms that never go out of style.",
    questions: [
      "Television",
      "Bicycle",
      "Wristwatch",
      "Sunglasses",
      "Backpack",
      "Headphones",
      "Camera Flash",
      "Umbrella",
      "Coffee Cup",
      "Desk Lamp",
      "Sneakers",
      "Acoustic Guitar",
      "Passport",
      "Keyring",
      "Notebook",
      "Desk Chair",
      "Pocket Knife",
      "Water Bottle",
      "Wall Clock",
      "Shopping Cart",
    ],
  },
  {
    id: "11",
    title: "History",
    icon: Icons.BookOpenText,
    intro:
      "Travel back through centuries of kingdoms, independence struggles, ancient artifacts, and unforgettable historical turning points.",
    questions: [
      "Independence Day",
      "Queen Victoria",
      "Ancient Pyramids",
      "British Empire",
      "World War II",
      "Lagos Colony",
      "Emancipation",
      "Traditional Ruler",
      "Royal Palace",
      "Colonization",
      "Bronze Sculptures",
      "Civil Rights Movement",
      "Ancient Scroll",
      "Stone Age",
      "Industrial Revolution",
      "Discovery of Fire",
      "First Republic",
      "Treaty Signing",
      "Monarchy",
      "Historical Museum",
    ],
  },
  {
    id: "12",
    title: "Travel",
    icon: Icons.AirplaneTilt,
    intro:
      "Pack your bags! Boarding passes, passport control, dream destinations, and wild adventures across the globe.",
    questions: [
      " Murtala Muhammed Airport",
      "Boarding Pass",
      "Window Seat",
      "Jet Lag",
      "Passport Control",
      "Tourist Map",
      "Hotel Room Key",
      "Souvenir Shop",
      "Backpacking",
      "Cruise Ship",
      "First Class Lounge",
      "Customs Declaration",
      "Luggage Tag",
      "Overhead Bin",
      "Flight Delay",
      "In-flight Meal",
      "Taxi Cab",
      "Beach Resort",
      "Mountain Hiking",
      "Road Trip",
    ],
  },
  {
    id: "13",
    title: "Politics",
    icon: Icons.Gavel,
    intro:
      "Campaign rallies, ballot boxes, manifestos, and high-stakes government drama. Can you talk politics without arguing?",
    questions: [
      " Ballot Box",
      "Campaign Rally",
      "Constituency",
      "Member of Parliament",
      "Senate President",
      "Governor's Mansion",
      "Supreme Court",
      "Political Manifesto",
      "Voter Card",
      "Party Primary",
      "Impeachment",
      "Cabinet Minister",
      "Press Briefing",
      "Diplomatic Mission",
      "Executive Order",
      "Opposition Party",
      "Polling Booth",
      "National Assembly",
      "Public Debate",
      "Secret Ballot",
    ],
  },
  {
    id: "14",
    title: "Art",
    icon: Icons.PaintBrush,
    intro:
      "Canvas splashes, gallery openings, sculptures, and creative expressions that capture the soul's deepest imagery.",
    questions: [
      "Oil Painting",
      "Sculpture",
      "Canvas Board",
      "Watercolors",
      "Art Gallery",
      "Pottery Wheel",
      "Sketchbook",
      "Charcoal Pencil",
      "Abstract Design",
      "Portrait Studio",
      "Color Palette",
      "Mural Wall",
      "Exhibition Opening",
      "Clay Modeling",
      "Calligraphy",
      "Artisan Market",
      "Easel Stand",
      "Creative Vision",
      "Masterpiece",
      "Stained Glass",
    ],
  },
  {
    id: "15",
    title: "Science",
    icon: Icons.Flask,
    intro:
      "Put on your lab coat! Chemical reactions, lab experiments, cosmic laws, and mind-bending physics formulas.",
    questions: [
      "Periodic Table",
      "Microscope",
      "Black Hole",
      "DNA Strand",
      "Quantum Physics",
      "Chemical Reaction",
      "Gravity Pull",
      "Solar System",
      "Atom Structure",
      "Laboratory Flask",
      "Speed of Light",
      "Test Tube",
      "Cell Nucleus",
      "Electric Circuit",
      "Magnetic Field",
      "Photosynthesis",
      "Ecosystem",
      "Supernova",
      "Thermal Energy",
      "Data Analysis",
    ],
  },
  {
    id: "16",
    title: "Relationships",
    icon: Icons.Heart,
    intro:
      "Love, dating text rules, red flags, green flags, and everything that makes relationships complicated and sweet.",
    questions: [
      "First Date",
      "Red Flags",
      "Green Flags",
      "Texting Back Fast",
      "Double Texting",
      "Talking Stage",
      "Situationship",
      "Anniversary Gift",
      "Romantic Dinner",
      "Long Distance",
      "Heart to Heart",
      "Love Language",
      "Compromise",
      "Sweet Apology",
      "Couple Goals",
      "Blind Date",
      "Proposal Ring",
      "Broken Trust",
      "Deep Connection",
      "Morning Text",
    ],
  },
];
